name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.5

      - name: Angular Dependencies
        run: npm install

      - name: Install Angular CLI
        run: |
          npm install @angular/cli

      - name: Build Angular Project
        run: npm run build -- --base-href="/gigya-applications/"

      - name: Debug GitHub Pages Deploy
        run: |
              echo "Current branch: $(git branch --show-current)"
              echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
              ls -la ./dist



      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ./dist
